In [1]:
#文本数据加载
data = open('task2_data').read()
#移除换行符
data = data.replace('\n','').replace('\r','')
print(data)

Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": an

In [2]:
#字符字母的去重处理
letters = list(set(data))
print(letters)
features = len(letters)
print(features)

['i', 'd', 'v', '"', 'p', 'r', 'a', 's', ':', '(', '.', 'k', 'o', 'n', 'g', 'u', 'z', ' ', ')', 't', 'L', 'e', 'c', 'A', ',', 'f', 'l', 'm', 'x', 'h', 'y', 'b', 'I']
33


In [3]:
#建立字典
#数字：字符字典
int_to_char = {a:b for a,b in enumerate(letters)}
print(int_to_char)
#字符：数字字典
char_to_int = {b:a for a,b in enumerate(letters)}
print(char_to_int)

{0: 'i', 1: 'd', 2: 'v', 3: '"', 4: 'p', 5: 'r', 6: 'a', 7: 's', 8: ':', 9: '(', 10: '.', 11: 'k', 12: 'o', 13: 'n', 14: 'g', 15: 'u', 16: 'z', 17: ' ', 18: ')', 19: 't', 20: 'L', 21: 'e', 22: 'c', 23: 'A', 24: ',', 25: 'f', 26: 'l', 27: 'm', 28: 'x', 29: 'h', 30: 'y', 31: 'b', 32: 'I'}
{'i': 0, 'd': 1, 'v': 2, '"': 3, 'p': 4, 'r': 5, 'a': 6, 's': 7, ':': 8, '(': 9, '.': 10, 'k': 11, 'o': 12, 'n': 13, 'g': 14, 'u': 15, 'z': 16, ' ': 17, ')': 18, 't': 19, 'L': 20, 'e': 21, 'c': 22, 'A': 23, ',': 24, 'f': 25, 'l': 26, 'm': 27, 'x': 28, 'h': 29, 'y': 30, 'b': 31, 'I': 32}


In [4]:
#time_step
time_step = 30

In [6]:
import numpy as np
from tensorflow.python.keras.utils.np_utils import to_categorical
#滑动窗口提取数据
def extract_data(data, slide):    
    x = []
    y = []    
    for i in range(len(data) - slide):
        x.append([a for a in data[i:i+slide]])
        y.append(data[i+slide])        
    return x,y
#字符到数字的批量转化
def char_to_int_Data(x,y, char_to_int):    
    x_to_int = []
    y_to_int = []
    for i in range(len(x)):
        x_to_int.append([char_to_int[char] for char in x[i]])
        y_to_int.append([char_to_int[char] for char in y[i]])    
    return x_to_int, y_to_int
#实现输入字符文章的批量处理，输入整个字符、滑动窗口大小、转化字典
def data_preprocessing(data, slide, num_letters, char_to_int):    
    char_Data = extract_data(data, slide)
    int_Data = char_to_int_Data(char_Data[0], char_Data[1], char_to_int)
    Input = int_Data[0]
    Output = list(np.array(int_Data[1]).flatten())
    Input_RESHAPED = np.array(Input).reshape(len(Input), slide)
    new = np.random.randint(0,10,size=[Input_RESHAPED.shape[0],Input_RESHAPED.shape[1],num_letters])
    for i in range(Input_RESHAPED.shape[0]):
        for j in range(Input_RESHAPED.shape[1]):
            new[i,j,:] = to_categorical(Input_RESHAPED[i,j],num_classes=num_letters)
    return new, Output

In [7]:
#字符串处理
# print(data)
X, y = data_preprocessing(data,time_step,features,char_to_int)
print(X[0,:,:])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [8]:
print(X[0,:,:].shape)

(30, 33)


In [9]:
print(X.shape,len(y))

(11160, 30, 33) 11160


In [10]:
#数据分离
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=0)
print(X.shape,X_train.shape,X_test.shape)
print(len(y),len(y_train),len(y_test))

(11160, 30, 33) (10044, 30, 33) (1116, 30, 33)
11160 10044 1116


In [11]:
#输出结果的格式转化
y_train_c = to_categorical(y_train,features)
print(y_train)
print(y_train_c)

[21, 21, 17, 17, 0, 17, 0, 14, 22, 7, 6, 21, 6, 17, 21, 17, 21, 21, 12, 11, 14, 26, 26, 19, 13, 23, 17, 13, 7, 0, 6, 17, 26, 14, 31, 7, 21, 21, 22, 12, 19, 0, 0, 17, 6, 13, 21, 5, 21, 17, 7, 17, 0, 6, 24, 17, 13, 26, 21, 27, 0, 0, 25, 26, 25, 7, 4, 20, 12, 17, 17, 21, 7, 13, 25, 31, 17, 14, 17, 0, 0, 12, 21, 21, 17, 0, 15, 14, 29, 13, 19, 21, 0, 1, 8, 17, 17, 21, 17, 0, 0, 0, 32, 26, 22, 26, 1, 7, 13, 0, 28, 2, 28, 2, 17, 27, 22, 7, 6, 2, 17, 22, 7, 6, 13, 17, 6, 29, 15, 23, 7, 17, 21, 6, 13, 17, 12, 17, 21, 1, 21, 22, 13, 9, 11, 19, 15, 1, 11, 0, 19, 15, 17, 13, 19, 19, 17, 17, 7, 1, 0, 19, 13, 26, 1, 32, 21, 21, 21, 27, 13, 17, 0, 13, 13, 17, 5, 27, 14, 7, 28, 17, 6, 6, 27, 22, 17, 7, 0, 27, 26, 19, 0, 17, 17, 17, 1, 17, 1, 17, 21, 7, 21, 19, 13, 19, 21, 13, 25, 21, 27, 17, 13, 13, 4, 21, 17, 19, 7, 13, 12, 0, 7, 4, 28, 0, 19, 27, 17, 16, 3, 30, 17, 27, 5, 13, 31, 17, 3, 17, 13, 21, 30, 17, 19, 12, 17, 12, 6, 17, 17, 11, 13, 21, 7, 29, 17, 2, 0, 19, 17, 15, 7, 10, 7, 13, 19, 21, 17, 

In [12]:
print(y_train_c.shape)

(10044, 33)


In [13]:
#建立LSTM模型
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
#LSTM层
model.add(LSTM(units=30, input_shape=(X_train.shape[1],X_train.shape[2]),activation='relu'))
#输出层
model.add(Dense(units=features,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 30)                7680      
_________________________________________________________________
dense (Dense)                (None, 33)                1023      
Total params: 8,703
Trainable params: 8,703
Non-trainable params: 0
_________________________________________________________________


In [14]:
#核心参数配置
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [15]:
#模型训练
model.fit(X_train,y_train_c,batch_size=1000,epochs=50)

Epoch 1/50
11/11 [==============================] - 19s 53ms/step - loss: 3.4749 - accuracy: 0.0746
Epoch 2/50
11/11 [==============================] - 0s 43ms/step - loss: 3.4193 - accuracy: 0.1277
Epoch 3/50
11/11 [==============================] - 0s 44ms/step - loss: 3.2753 - accuracy: 0.1309
Epoch 4/50
11/11 [==============================] - 0s 43ms/step - loss: 3.0727 - accuracy: 0.1420
Epoch 5/50
11/11 [==============================] - 0s 42ms/step - loss: 2.9698 - accuracy: 0.1705
Epoch 6/50
11/11 [==============================] - 0s 43ms/step - loss: 2.9236 - accuracy: 0.1798
Epoch 7/50
11/11 [==============================] - 0s 42ms/step - loss: 2.9064 - accuracy: 0.1596
Epoch 8/50
11/11 [==============================] - 0s 42ms/step - loss: 2.8769 - accuracy: 0.1937
Epoch 9/50
11/11 [==============================] - 0s 40ms/step - loss: 2.8552 - accuracy: 0.1830
Epoch 10/50
11/11 [==============================] - 0s 40ms/step - loss: 2.8468 - accuracy: 0.1824
Epoch 11

In [16]:
#训练数据的预测
y_train_predict = model.predict_classes(X_train)
print(y_train_predict)

C:\Users\zheng\AppData\Roaming\Python\Python38\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[21 21 17 ... 21 13  1]


In [17]:
#预测结果转化到字符
y_train_predict_char = [int_to_char[i] for i in y_train_predict]
print(y_train_predict_char)

['e', 'e', ' ', ' ', 'i', ' ', 'i', 'g', 'c', ' ', 'a', 't', 'a', ' ', 'e', ' ', 'n', 'c', 'o', 'a', 'g', 's', 'l', 't', 'n', 'A', ' ', 'n', 't', 'i', 'a', ' ', 'l', 'g', 'b', 's', 't', 'a', 'c', 'o', 'a', 'i', 's', ' ', 'a', 'n', 'o', 'u', 'h', ' ', ' ', ' ', 'i', 'a', ',', ' ', 'n', 'n', 'e', 'm', 'i', 'i', 'f', 'l', 'o', 's', 's', 'o', 'a', ' ', ' ', 'e', 's', 'n', 'f', 'i', ' ', 'g', ' ', 'i', 'i', 'o', 'o', 'e', ' ', 'i', 'u', 'g', 'h', 'n', 't', 'e', 'i', 'd', 'i', ' ', ' ', 'a', ' ', 'a', 'i', 'i', 'I', 'l', 'c', 'l', 't', 's', 'n', 'i', 'c', 'n', 'c', 'v', ' ', 'a', 'c', 's', 'a', 'v', ' ', 'c', 't', 'a', 'n', ' ', 'h', 'h', 'u', 'a', 's', ' ', 'e', 'a', 'n', ' ', 'e', ' ', 't', 'd', 'e', 'c', 'n', '(', 'f', ' ', 'u', 'd', 'a', 'm', 't', 'u', ' ', 'n', 's', 'c', ' ', ' ', 's', 'd', 's', 't', 'n', 'c', 'a', 'I', 'h', 'e', 'e', 'a', 'n', ' ', 'i', 'n', 'n', ' ', 'u', 'm', 'o', 's', 's', ' ', ' ', 'a', 'm', 'c', ' ', 's', 'i', 'm', 'n', 't', 'i', ' ', ' ', ' ', 'a', ' ', 't', ' ',

In [18]:
#准确率
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train,y_train_predict)
print(accuracy_train)

0.7013142174432497


In [19]:
#测试数据的预测
y_test_predict = model.predict_classes(X_test)
y_test_predict_char = [int_to_char[i] for i in y_test_predict]
print(y_test_predict_char)

['a', 'u', 'a', 'g', 'n', 'n', 'l', 'i', ' ', 'e', 'c', 'v', 'm', 'g', 'o', 'u', ' ', 'c', 'i', ' ', 'n', 'a', 'i', 't', 'e', 'm', 'g', 'a', 'A', 'u', ' ', 's', 'u', 'a', 'a', 'c', 't', ' ', 'm', 'e', 'i', 'a', 'c', 'm', ' ', 'l', 'm', 'f', 's', 'l', 's', 'n', 'n', 'n', ' ', 'i', 'e', 'e', ' ', 'h', 'm', ' ', 'e', 'd', 'r', ' ', 'n', 'l', 'c', ' ', 'v', 'r', ' ', 'i', 'o', 'u', 'c', 'e', 'e', 'l', 'i', ' ', 'e', ' ', 'c', 'A', 'g', ' ', 'n', 'o', 'i', 'i', 'i', 'h', 'a', 'a', 'c', ' ', 'n', 'e', 'n', 'i', 'u', 'm', 'I', 'a', 'd', 'c', ' ', ' ', 't', 's', 'b', ' ', 's', 's', 'e', 'g', ' ', 'e', ' ', 'e', 'a', 'n', 'f', 't', 'b', 'o', 'i', 'i', 'l', 'g', ' ', 'm', 'n', 'c', 'e', 's', ' ', 't', 'g', 'd', ' ', 'v', 'v', 't', 'g', 'i', ' ', 'h', 'g', ' ', 'm', 'h', 'a', 'e', ' ', 'a', 'i', ' ', ' ', ' ', ' ', 'a', 'e', 'g', 'i', 'm', 'd', 'i', 'e', 'i', 'i', ' ', 'i', 'a', 'a', 'o', ' ', 'o', 'u', 'a', ' ', 'o', 'c', ' ', 'f', 'e', ' ', 't', 'f', 'e', 'c', ' ', 'g', 'a', 'h', 'n', ' ', 'g',

C:\Users\zheng\AppData\Roaming\Python\Python38\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [20]:
accuracy_test = accuracy_score(y_test,y_test_predict)
print(accuracy_test)

0.681899641577061


In [21]:
#新字符串的预测
new_letters = 'Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines'
X_new,y_new = data_preprocessing(new_letters,time_step,features,char_to_int)
print(X_new.shape,len(y_new))

(79, 30, 33) 79


In [22]:
y_new_predict = model.predict_classes(X_new)
print(y_new_predict)

[19  6 12  6  7  7 27 21  7 17  6  6  6 26  0  1 17 27  6 22 29  0 13 21
 17  0 13 19 21  6 26  0 14 21 13 22 21 17 17  0  6 17  0 13 19 21 26 26
  0 14 21 13 22 21 17  1 21 27 12 13  7 17 15  6 21 21  1 17 31 30 17 27
  6 22 29  0 13 22  7]


C:\Users\zheng\AppData\Roaming\Python\Python38\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [23]:
y_new_predict_char = [int_to_char[i] for i in y_new_predict]
print(y_new_predict_char)

['t', 'a', 'o', 'a', 's', 's', 'm', 'e', 's', ' ', 'a', 'a', 'a', 'l', 'i', 'd', ' ', 'm', 'a', 'c', 'h', 'i', 'n', 'e', ' ', 'i', 'n', 't', 'e', 'a', 'l', 'i', 'g', 'e', 'n', 'c', 'e', ' ', ' ', 'i', 'a', ' ', 'i', 'n', 't', 'e', 'l', 'l', 'i', 'g', 'e', 'n', 'c', 'e', ' ', 'd', 'e', 'm', 'o', 'n', 's', ' ', 'u', 'a', 'e', 'e', 'd', ' ', 'b', 'y', ' ', 'm', 'a', 'c', 'h', 'i', 'n', 'c', 's']


In [24]:
for i in range(0,X_new.shape[0]-30):
    print(new_letters[i:i+30],'--predict new letter is>>>',y_new_predict_char[i])

Artificial intelligence (AI),  --predict new letter is>>> t
rtificial intelligence (AI), s --predict new letter is>>> a
tificial intelligence (AI), so --predict new letter is>>> o
ificial intelligence (AI), som --predict new letter is>>> a
ficial intelligence (AI), some --predict new letter is>>> s
icial intelligence (AI), somet --predict new letter is>>> s
cial intelligence (AI), someti --predict new letter is>>> m
ial intelligence (AI), sometim --predict new letter is>>> e
al intelligence (AI), sometime --predict new letter is>>> s
l intelligence (AI), sometimes --predict new letter is>>>  
 intelligence (AI), sometimes  --predict new letter is>>> a
intelligence (AI), sometimes c --predict new letter is>>> a
ntelligence (AI), sometimes ca --predict new letter is>>> a
telligence (AI), sometimes cal --predict new letter is>>> l
elligence (AI), sometimes call --predict new letter is>>> i
lligence (AI), sometimes calle --predict new letter is>>> d
ligence (AI), sometimes called --predict